### ISSUE TITLE
TODO LIST

### ISSUE THREAD

**Issue by avenger11** [avenger11/Apple-HomePlay#3]
- [ ] Have one place to setup all entities instead of inside the card
    - [x] group doesn't work
    - [x] hass-lovelace_gen is not updated since 2021 and just bug the config file 
    - [x] input_text does not work
    - [x] anchor does not work through multiple file only on one. worst, does not work in a value template.
    - [ ] Out-of Idea ...
